name: Staging Terraform Pipeline

on:
  push:
    branches:
      - '**'
    paths:
      - 'terraform/aws/staging/**'

  pull_request:
    types: [closed]
    branches:
      - dev
    paths:
      - 'terraform/aws/staging/**'

env:
  TF_WORKING_DIR: terraform/aws/staging
  AWS_REGION: ${{ secrets.AWS_REGION }}

