name: Staging Terraform Pipeline

on:
  push:
    branches:
      - '**'
    paths:
      - 'terraform/aws/staging/**'

  pull_request:
    types: [closed]
    branches:
      - dev
    paths:
      - 'terraform/aws/staging/**'

env:
  TF_WORKING_DIR: terraform/aws/staging
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform-check:
    if: github.ref != 'refs/heads/dev'
    runs-on: ubuntu-latest
    name: Terraform Validate and Plan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init (with S3 backend)
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

      - name: Terraform Plan
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} plan
      
      - name: Terraform Validate
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} validate

      