name: Terraform CI/CD for Staging and Production

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev
    paths:
      - 'terraform/aws/staging/**'
      - 'terraform/aws/production/**'

jobs:
  detect-changes:
    name: Detect Changed Paths
    runs-on: ubuntu-latest
    outputs:
      staging: ${{ steps.filter.outputs.staging }}
      production: ${{ steps.filter.outputs.production }}
    steps:
      - uses: actions/checkout@v3

      - name: Check changed paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            staging:
              - 'terraform/aws/staging/**'
            production:
              - 'terraform/aws/production/**'

  terraform-staging:
    name: Terraform Plan & Apply - Staging
    needs: detect-changes
    if: needs.detect-changes.outputs.staging == 'true'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: terraform/aws/staging
      AWS_REGION: ${{ secrets.AWS_REGION_STAGING }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials (Staging)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

      - name: Terraform Plan
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} plan

      - name: Terraform Validate
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} validate

      - name: Terraform Apply
        if: github.event.pull_request.merged == true
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} apply -auto-approve

  terraform-production:
    name: Terraform Plan & Apply - Production
    needs: detect-changes
    if: needs.detect-changes.outputs.production == 'true'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://console.aws.amazon.com/
    env:
      TF_WORKING_DIR: terraform/aws/production
      AWS_REGION: ${{ secrets.AWS_REGION_PROD }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials (Production)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

      - name: Terraform Plan
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} plan

      - name: Terraform Validate
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} validate

      - name: Terraform Apply
        if: github.event.pull_request.merged == true
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} apply -auto-approve
